[project]
name = "nepa-admin"
version = "0.1.0"
description = "Interface para o banco de dados do NEPA"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-admin[export,sqlalchemy-with-utils]>=2.0.2",
    "flask-argon2>=0.3.0.0",
    "flask-babel>=4.0.0",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "gunicorn>=25.1.0",
    "psycopg[binary,pool]>=3.3.3",
    "python-dotenv>=1.2.2",
    "python-slugify[unidecode]>=8.0.4",
]

[dependency-groups]
devtools = [
    "ruff>=0.15.5",
    "ty>=0.0.21",
]

[tool.ruff]
src = ["nepav2"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["A", "B", "C4", "E", "F", "I", "PTH", "RET", "S", "SIM", "TC", "TID", "UP", "W", "YTT"]
ignore = ["E501"]

exclude = [
    ".venv",
    "*.pyi",
    ".git",
    ".github",
    ".ruff_cache",
    "static",
    "uploads",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
